project_name: amped

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256



changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
